server:
  port: 8090

spring:
  application:
    name: gateway-service

  cloud:
    nacos:
      discovery:
        enabled: true
        server-addr: nacos:8848
        namespace: dev
        group: COURSEHUB_GROUP
        register-enabled: true
        ephemeral: true  # ?????????? Nacos ?????
        heart-beat-interval: 5000  # ???? 5s
        heart-beat-timeout: 15000  # ???? 15s
    gateway:
      discovery:
        locator:
          enabled: true          # ???????
          lower-case-service-id: true
      # ????
      routes:
        # ??????
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/users/**,/api/auth/**
          filters:
            - StripPrefix=1  # ?? /api ??
              # Auth ?? (????)
          # Catalog Service ??
        - id: catalog-service
          uri: lb://catalog-service
          predicates:
            - Path=/api/courses/**
          filters:
             - StripPrefix=1
            # Enrollment Service ??
               # Enrollment Service ??
        - id: enrollment-service
          uri: lb://enrollment-service
          predicates:
            - Path=/api/enrollments/**
          filters:
            - StripPrefix=1
      # ????
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOriginPatterns: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - PATCH
            allowedHeaders: "*"
            allowCredentials: true
            maxAge: 3600

# JWT??
jwt:
  secret: "MySecretKeyForJWT2024CourseCloudSystemVeryLongAndSecure1234567890ABCDEFGHIJKLMNOPQRSTUVWXYZ"
  expiration: 86400000


logging:
  level:
    com.zjgsu.cyd.coursecloud.gatewayservice: DEBUG
    org.springframework.cloud.gateway: DEBUG
    root: INFO
    com.alibaba.cloud.nacos: DEBUG
    com.alibaba.nacos: DEBUG


management:
  endpoints:
    web:
      exposure:
        include: health,gateway,info,mappings
  endpoint:
    health:
      show-details: always  # ????????? Nacos ??????
